import type { Metadata } from "next";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";
import "./globals.css";
import { Navbar1 } from "@/components/widgets/navbar1";
import { EcommerceFooter1 } from "@/components/widgets/ecommerce-footer1";
import { SidebarWrapper } from "@/components/widgets/sidebar-wrapper";
import { ThemeProvider } from "@/components/theme-provider";
import { CartProvider } from "@/contexts/CartContext";
import UserProvider from "@/contexts/UserContext";
import { WishlistProvider } from "@/contexts/WishlistContext";
import { WebVitals } from "@/components/widgets/web-vitals";
import { PageTransition, LocaleTransition } from "@/components/widgets/page-transition";

const montserrat = localFont({
  src: "../../public/fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html
      lang={locale}
      dir={dir}
      suppressHydrationWarning
      className={`${montserrat.variable} h-full antialiased`}
    >
      <head>
        <link rel="preconnect" href="https://deifkwefumgah.cloudfront.net" />
        <link rel="preconnect" href="https://res.cloudinary.com" />
        <link rel="dns-prefetch" href="https://deifkwefumgah.cloudfront.net" />
        <link rel="dns-prefetch" href="https://res.cloudinary.com" />
      </head>
      <body className="flex min-h-full flex-col">
        <WebVitals />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <LocaleTransition>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
            disableTransitionOnChange
          >
            <UserProvider>
              <CartProvider>
              <WishlistProvider>
                <Navbar1 />
                <div className="flex flex-1 container mx-auto px-4">
                  <SidebarWrapper />
                  <main className="flex-1 min-w-0">
                    <PageTransition>{children}</PageTransition>
                  </main>
                </div>
                <EcommerceFooter1 />
              </WishlistProvider>
            </CartProvider>
            </UserProvider>
          </ThemeProvider>
          </LocaleTransition>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
